{
  "build": {
    "command": "echo 'No build needed'"
  },
  "redirects": [
    {
      "source": "/api/:path*",
      "destination": "https://app-lin-git-main-linjunyuans-projects.vercel.app/api/:path*",
      "status": 200
    }
  ],
  "headers": [
    {
      "source": "/api/*",
      "headers": [
        {
          "key": "Access-Control-Allow-Origin",
          "value": "https://wonderful-kelpie-6dd57e.netlify.app"
        },
        {
          "key": "Access-Control-Allow-Methods",
          "value": "GET, POST, PUT, DELETE, OPTIONS"
        },
        {
          "key": "Access-Control-Allow-Headers",
          "value": "Content-Type, Authorization, X-Requested-With"
        },
        {
          "key": "Access-Control-Allow-Credentials",
          "value": "true"
        }
      ]
    }
  ]
}
